# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param synth.incrementalSynthesisCache {C:/Users/Vincent G/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-31280-GANSZ-DESKTOP/incrSyn}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Vincent G/Desktop/gsplat/gsplat.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Vincent G/Desktop/gsplat/gsplat.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Vincent G/Desktop/gsplat/gsplat.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  {C:/Users/Vincent G/Desktop/gsplat/mem/gaussian_lut.mem}
  {C:/Users/Vincent G/Desktop/gsplat/mem/test_gradient.mem}
  {C:/Users/Vincent G/Desktop/gsplat/mem/test_overlap.mem}
  {C:/Users/Vincent G/Desktop/gsplat/mem/test_splats.mem}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/Vincent G/Desktop/gsplat/src/alpha_blender.vhd}
  {C:/Users/Vincent G/Desktop/gsplat/gsplat.srcs/sources_1/imports/src/camera_controller.vhd}
  {C:/Users/Vincent G/Desktop/gsplat/src/clk_gen.vhd}
  {C:/Users/Vincent G/Desktop/gsplat/src/framebuffer.vhd}
  {C:/Users/Vincent G/Desktop/gsplat/src/gaussian_lut.vhd}
  {C:/Users/Vincent G/Desktop/gsplat/src/render_controller.vhd}
  {C:/Users/Vincent G/Desktop/gsplat/src/splat_rasterizer.vhd}
  {C:/Users/Vincent G/Desktop/gsplat/src/splat_rom.vhd}
  {C:/Users/Vincent G/Desktop/gsplat/src/vga_timing.vhd}
  {C:/Users/Vincent G/Desktop/gsplat/src/vga_controller.vhd}
  {C:/Users/Vincent G/Desktop/gsplat/src/top_gsplat.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Vincent G/Desktop/gsplat/constrs/gsplat.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Vincent G/Desktop/gsplat/constrs/gsplat.xdc}}]


synth_design -top top_gsplat -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_gsplat.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_gsplat_utilization_synth.rpt -pb top_gsplat_utilization_synth.pb"
