----------------------------------------------------------------------------------
-- gaussian_lut.vhd
-- Gaussian weight lookup table
-- Input:  8-bit normalized squared distance (d2_norm = d^2 * 255 / r^2)
-- Output: 8-bit weight approximating exp(-d2_norm * k)
-- 256 entries, initialized from gaussian_lut.mem
----------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gaussian_lut is
    Port (
        clk      : in  STD_LOGIC;
        d2_norm  : in  STD_LOGIC_VECTOR(7 downto 0);
        weight   : out STD_LOGIC_VECTOR(7 downto 0)
    );
end gaussian_lut;

architecture Behavioral of gaussian_lut is

    type lut_type is array (0 to 255) of std_logic_vector(7 downto 0);

    -- Gaussian weight LUT: weight = round(255 * exp(-3.0 * i / 255))
    -- Initialized inline; can also be loaded from .mem file
    signal lut : lut_type := (
        -- Generated by generate_gaussian_lut.py (sigma_factor=3.0)
        -- i=0..15
        X"FF", X"FC", X"F9", X"F6", X"F3", X"F0", X"EE", X"EB",
        X"E8", X"E5", X"E3", X"E0", X"DD", X"DB", X"D8", X"D6",
        -- i=16..31
        X"D3", X"D1", X"CE", X"CC", X"CA", X"C7", X"C5", X"C3",
        X"C0", X"BE", X"BC", X"BA", X"B7", X"B5", X"B3", X"B1",
        -- i=32..47
        X"AF", X"AD", X"AB", X"A9", X"A7", X"A5", X"A3", X"A1",
        X"9F", X"9D", X"9C", X"9A", X"98", X"96", X"94", X"93",
        -- i=48..63
        X"91", X"8F", X"8E", X"8C", X"8A", X"89", X"87", X"86",
        X"84", X"82", X"81", X"7F", X"7E", X"7C", X"7B", X"7A",
        -- i=64..79
        X"78", X"77", X"75", X"74", X"73", X"71", X"70", X"6F",
        X"6D", X"6C", X"6B", X"6A", X"68", X"67", X"66", X"65",
        -- i=80..95
        X"63", X"62", X"61", X"60", X"5F", X"5E", X"5D", X"5C",
        X"5B", X"59", X"58", X"57", X"56", X"55", X"54", X"53",
        -- i=96..111
        X"52", X"51", X"51", X"50", X"4F", X"4E", X"4D", X"4C",
        X"4B", X"4A", X"49", X"48", X"48", X"47", X"46", X"45",
        -- i=112..127
        X"44", X"43", X"43", X"42", X"41", X"40", X"40", X"3F",
        X"3E", X"3D", X"3D", X"3C", X"3B", X"3B", X"3A", X"39",
        -- i=128..143
        X"39", X"38", X"37", X"37", X"36", X"35", X"35", X"34",
        X"33", X"33", X"32", X"32", X"31", X"31", X"30", X"2F",
        -- i=144..159
        X"2F", X"2E", X"2E", X"2D", X"2D", X"2C", X"2C", X"2B",
        X"2B", X"2A", X"2A", X"29", X"29", X"28", X"28", X"27",
        -- i=160..175
        X"27", X"26", X"26", X"25", X"25", X"25", X"24", X"24",
        X"23", X"23", X"23", X"22", X"22", X"21", X"21", X"21",
        -- i=176..191
        X"20", X"20", X"1F", X"1F", X"1F", X"1E", X"1E", X"1E",
        X"1D", X"1D", X"1D", X"1C", X"1C", X"1C", X"1B", X"1B",
        -- i=192..207
        X"1B", X"1A", X"1A", X"1A", X"19", X"19", X"19", X"19",
        X"18", X"18", X"18", X"17", X"17", X"17", X"17", X"16",
        -- i=208..223
        X"16", X"16", X"16", X"15", X"15", X"15", X"15", X"14",
        X"14", X"14", X"14", X"13", X"13", X"13", X"13", X"12",
        -- i=224..239
        X"12", X"12", X"12", X"12", X"11", X"11", X"11", X"11",
        X"11", X"10", X"10", X"10", X"10", X"10", X"10", X"0F",
        -- i=240..255
        X"0F", X"0F", X"0F", X"0F", X"0E", X"0E", X"0E", X"0E",
        X"0E", X"0E", X"0D", X"0D", X"0D", X"0D", X"0D", X"0D"
    );

    signal weight_reg : std_logic_vector(7 downto 0) := (others => '0');

begin

    process(clk)
    begin
        if rising_edge(clk) then
            weight_reg <= lut(to_integer(unsigned(d2_norm)));
        end if;
    end process;

    weight <= weight_reg;

end Behavioral;
